### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by by-pm** [ESPWortuhr/Wortuhr#168]
Hi, can someone help me with this error when i try to upload my code to my nodemcu?

`*** [upload] UnboundLocalError : local variable 'port' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\10457\.platformio\packages\tool-scons\scons-local-4.4.0\SCons\Action.py", line 1318, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "C:\Users\10457\.platformio\packages\tool-scons\scons-local-4.4.0\SCons\Util.py", line 737, in __call__
    return self.method(*nargs, **kwargs)
  File "C:\Users\10457\.platformio\penv\lib\site-packages\platformio\builder\tools\pioupload.py", line 113, in AutodetectUploadPort
    UPLOAD_PORT=SerialPortFinder(
  File "C:\Users\10457\.platformio\penv\lib\site-packages\platformio\device\finder.py", line 156, in find
    return best_port or port
UnboundLocalError: local variable 'port' referenced before assignment
================================================= [FAILED] Took 13.14 seconds =================================================

 *  The terminal process "C:\Users\10457\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload', '--environment', 'nodemcuv2'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
`

**Comment by dbambus** [comment]
Hey, 

has it been solved already ? That error is not related to the code itself, it is more likely to your upload setup.
